### ISSUE TITLE
Return data in useSearchForPassagesByBookCodes

### ISSUE THREAD

**Issue by Valyukhov** [unfoldingWord/proskomma-react-hooks#16]
![изображение](https://user-images.githubusercontent.com/74174349/147587540-34583a4a-0def-4fd5-817a-44b1b05f57e7.png)
In useSearchForPassagesByBookCode we get  data in return. I think it will be usefull to have this in useSearchForPassagesByBookCodes.

**Comment by klappy** [comment]
This should be addressed in PR #18 and will result in a new release.

**Comment by klappy** [comment]
published to NPM as v1.4.1

**Comment by klappy** [comment]
<img width="872" alt="Screen Shot 2022-01-06 at 11 55 25 AM" src="https://user-images.githubusercontent.com/118073/148420154-f09f5f67-9e42-46aa-a6f3-75d337859ce4.png">
