### ISSUE TITLE
USFM strings permanently in scope in useProskomma?

### ISSUE THREAD

**Issue by mvahowe** [unfoldingWord/proskomma-react-hooks#2]
Discussion on #1 helped me to notice how useProskomma is managing document state. As @klappy  says: "Update the documents array and the import will run".

I think this means that all imported documents are in scope, as USFM strings, for the lifetime of the hook? This raises several concerns for me:

1. This mechanism at least doubles the RAM footprint, since each document is stored both as a string and within Proskomma. (In the case of syntax trees that's potentially a very big deal.)
2. In some cases (including the current version of Chaliki) there are no USFM strings, because Chaliki uses the serialized format. In other cases the document content would be USX or TSV or something else.
3. If/when we want to use verse mapping, we need to import VRS files which attach to already-imported documents.

The underlying issue, I think, is that the current hook uses Proskomma as if it's a function that performs transforms on an array of import documents. But Proskomma - like most models - is very, very stateful.

If we replaced Proskomma with PostgreSQL, we wouldn't consider storing all the DBMS content in an array in the view. We'd use a combination of `select`, `insert`, `update` and `drop` queries to read and write state. I think we should be aiming for something similar for Proskomma.

**Comment by klappy** [comment]
This should now be addressed in v1.x
