### ISSUE TITLE
usePassage crashes on bad reference

### ISSUE THREAD

**Issue by eliaspinero** [unfoldingWord/proskomma-react-hooks#20]
When the reference is 3JN 1:1 the code works, but whenever we try changing that value the code crashes.

Error: "Uncaught TypeError: Cannot read properties of undefined (reading 'length')"

If we initialize the reference to "3JN 1:" we get this error: "Uncaught TypeError: Cannot destructure property 'groups' of 'r.match(...)' as it is null."

You can see this yourself at: https://github.com/Proskomma/diegesis-reboot/tree/elias-pinero-browsePassage

**Comment by klappy** [comment]
Can you try on the latest release(s)? This should be resolved now.

The last 1.x should address it and the 2.x release as well, however, you may need to update your usage of `useCatalog` when updating to v2.x
